### ISSUE TITLE
This plugin no longer works after firmware update

### ISSUE THREAD

**Issue by seanxushen** [donavanbecker/homebridge-platform-wemo#132]
I have a Wemo Light switch and a Wemo link with four bulbs (grouped to two groups). Before the firmware upgrade, everything works fine with Homebridge. But After the firmware upgrade, those devices are still appear on the Homekit (as off), and I can not operate them any more (on/off/dimm are all useless).

The firmware now is Wemo_WW_2.00.11054.PVR-OWRT-LS (for Light Switch) and Wemo_WW_2.00.11054.PVR-OWRT-Link (for Wemo link).

**Comment by seanxushen** [comment]
Further testing , clear the assessories cache, my switch and bulbs disappeared. Basically plugin does not find those devices. Tried  homebridge-Wemo plug-in, same problem.

**Comment by ehemmete** [comment]
I am seeing the same problem.  Could you please share your config.xml with the manual device entries?  My service fails to load whenever I try to add that key.

**Comment by ukypayne** [comment]
Thank you for this. I had the same issue where I couldn't see any devices without specifying the 49153 port. Adding that and it fixed it instantly. I am not sure if I am having this problem since I have my IoT things on a separate VLAN from my Homebridge, but this is very useful info that should be posted with the readme.
